name: Ex-2
on: push
jobs:
  editorconfig:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: editorconfig-checker/action-editorconfig-checker@main
        - run: editorconfig-checker
  markdown-cli:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: |
            npm i -g cli-markdown
          name: install markdown-cli
          
        - run: md **/*.md
          name: run markdown-cli
  Build:
    needs: [editorconfig]
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh      
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Linting:
    needs: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download Artifact # Name of the step
        uses: actions/download-artifact@v4 # Action to use
        with: # Parameters for the action
          name: code # Name of the artifact to download. Optional. If unspecified, all artifacts for the run are downloaded.
          path: .
      - name: run linting
        uses: super-linter/super-linter/slim@v7 
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true 
